### ISSUE TITLE
Duplicates in Windows environments

### ISSUE THREAD

**Issue by kozmaz87** [conda/conda-pack#153] opened 2020-11-01 03:19 UTC
The zip compression therefore does not even work because it gets confused about 2 duplicate files in the same archive. 

The tar does seemingly because tar files have an order and it simply seems to overwrite everything in order but then there is a reliability problem to the whole setup. Sometimes the moved env works sometimes it does not depending on what order the tar file put the files in(I guess). After this running PyInstaller is a 50% chance of failure. I am thinking of working around this by preventing conda from using hard linking in ntfs because clearly this is not a thing that works as of yet.

My setup is conda 4.8.3 (that conda-pack updates to 4.9.1 when it is installed) and while conda-pack works perfectly for linux, it fails most of the time for windows :(

![image](https://user-images.githubusercontent.com/4070837/97794378-0fbc5080-1bf1-11eb-96c2-e92738b8030c.png)

**Comment by mcg1969** [comment] 2020-11-14 22:54
Thank you for the report—we definitely could use more Windows expertise to help clean up some of these issues.

Regarding conda being upgraded to 4.9.1, though—that's definitely conda's fault, not conda-pack's. It tries to update itself every time you install something in its environment, unless you configure it to do otherwise; e.g.
```
conda config --set auto_update_conda false
```

**Comment by mcg1969** [comment] 2020-11-14 22:58
After a bit of review I'm going to close this as a duplicate of #88 ... but again thank you for the report!

**Closed by mcg1969** 2020-11-14 22:58 UTC
