### ISSUE TITLE
File not found error when creating .zip on OSX

### ISSUE THREAD

**Issue by djhoese** [conda/conda-pack#114] opened 2020-06-12 15:17 UTC
I'm running conda-pack on Travis CI OSX with `-j -1` and found a bug in my code that was saving to a `.zip` file when I meant to be saving `.tar.gz`. What was interesting though was that the `.tar.gz` builds work fine, but the `.zip` builds fail. The error I'm seeing in the log:

```
Traceback (most recent call last):
  File "/Users/travis/miniconda/envs/test/lib/python3.7/site-packages/conda_pack/cli.py", line 148, in main
    ignore_editable_packages=args.ignore_editable_packages)
  File "/Users/travis/miniconda/envs/test/lib/python3.7/site-packages/conda_pack/core.py", line 466, in pack
    zip_symlinks=zip_symlinks, zip_64=zip_64)
  File "/Users/travis/miniconda/envs/test/lib/python3.7/site-packages/conda_pack/core.py", line 333, in pack
    packer.add(f)
  File "/Users/travis/miniconda/envs/test/lib/python3.7/site-packages/conda_pack/core.py", line 929, in add
    self.archive.add(file.source, file.target)
  File "/Users/travis/miniconda/envs/test/lib/python3.7/site-packages/conda_pack/formats.py", line 207, in add
    self._add(source, target)
  File "/Users/travis/miniconda/envs/test/lib/python3.7/site-packages/conda_pack/formats.py", line 291, in _add
    self.archive.write(source, target)
  File "/Users/travis/miniconda/envs/test/lib/python3.7/zipfile.py", line 1730, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/Users/travis/miniconda/envs/test/lib/python3.7/zipfile.py", line 518, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/travis/miniconda/pkgs/libblas-3.8.0-16_openblas/lib/libblas.3.dylib'
```

Any ideas based on this limited information what might be going on here? I can try to provide more information if needed, but as for the long term I didn't even mean to be making a `.zip` file so this won't be effecting me anymore.

Not sure this will provide any good information but here is the failing travis job: https://travis-ci.org/github/ssec/sift/jobs/697641675

conda-pack version:

```
conda-pack         conda-forge/noarch::conda-pack-0.4.0-py_0
```

**Comment by mcg1969** [comment] 2020-07-03 17:50
Duplicate of #99. 
Can you please try adding `--zip-symlinks` to your conda-pack command?

**Comment by mcg1969** [comment] 2020-07-03 17:51
(If I'm wrong that this is a duplicate, please feel free to reopen)

**Closed by mcg1969** 2020-07-03 17:51 UTC

**Comment by djhoese** [comment] 2020-07-03 19:22
I'm not sure this *isn't* a duplicate so I'm ok with the close. And like I mentioned I didn't intend to make this .zip file and I only see the issue on OSX so closing this seems fine to me. Thanks.
