### ISSUE TITLE
CondaPackError : Files managed by conda were found to have been deleted/overwritten

### ISSUE THREAD

**Issue by spladityapramanta** [conda/conda-pack#98] opened 2020-01-15 03:31 UTC
Hi, I have seen some of conda-pack updates regarding this issues and I have upgraded my conda-pack to the latest version but the problem is still there.

**A bit background story:**
Basically I have two environments which actually if I tried to clone (or move using .yml and spec-list.txt), it throws error because the package probably are obsolete/deprecated/not supported anymore because it was created on Jan 2018. So I try to use conda-pack to see if it can wrap the envs.
![conda-pack_error](https://user-images.githubusercontent.com/15991742/72400160-f38f1600-377a-11ea-88b0-955533ef914a.JPG)

_CondaPackError:
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- pandas='0.22.0'
- pip='9.0.3'
- util-linux='2.21'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred)._

When running conda list on those packages:
_# Name                    Version                   Build  Channel
geopandas                 0.4.0                     <pip>
pandas                    0.22.0                   py36_0    conda-for_ge

_# Name                    Version                   Build  Channel
pip                       9.0.3                    py36_0    conda-forge_

_# Name                    Version                   Build  Channel
util-linux                2.21                          0_

Anyone could help on these?

PS: updating the package is not an option because it might impact the apps/code that run inside those envs.

**Comment by frascuchon** [comment] 2020-01-22 13:00
Hi @spladityapramanta

Are your conda envioments created in a custom location ? I have the same problem just when I try to pack an environment created out of conda env folder (with `--prefix` argument)

**Comment by mcg1969** [comment] 2020-09-07 04:32
@spladityapramanta sorry for the long delay here. Usually what this means, in my experience, is that the package cache no longer has a copy of the packages in the environment. So unfortunately, the same mechanism conda requires to clone an environment is needed be conda-pack to turn it into an archive.

**Comment by xhochy** [comment] 2020-09-07 14:12
Actually, this rather sounds like files from these packages are missing. Either these files were deleted accidentally or as the message says, were overriden as you have used pip to install files. Can you post the full output of `pip list` and `conda list`?

**Comment by Phillip-M-Feldman** [comment] 2020-09-18 23:23
I'm seeing a similar issue, with messages like the the one shown below.  The part of the error message about pip is spurious, because I have learned from hard experience that one should NEVER use pip under any circumstances.

(py38) >conda-pack -n py38
Collecting packages...
CondaPackError:
Files managed by conda were found to have been deleted/overwritten in the following packages:

- python='3.8.5'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).

When I run conda list, I get the output shown below.  As far as I can tell, there is only one version of each package.  The list shows that two items came from pypi, but I don't use pip, so I'm unclear as to how these could have gotten installed.

(py38) >conda list
# packages in environment at C:\ProgramData\Anaconda3\envs\py38:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0
alabaster                 0.7.12                     py_0
anaconda                  custom                   py38_1
anaconda-client           1.7.2                    py38_0
anaconda-project          0.8.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38he774522_1
asn1crypto                1.4.0                      py_0
astroid                   2.4.2                    py38_0
astropy                   4.0.1.post1      py38he774522_1
astroquery                0.4.1              pyh9f0ad1d_0    conda-forge
atomicwrites              1.4.0                      py_0
attrs                     20.2.0                     py_0
autopep8                  1.5.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.shutil_get_terminal_size 1.0.0                    py38_2
bcrypt                    3.2.0            py38he774522_0
beautifulsoup4            4.9.1                    py38_0
bitarray                  1.5.3            py38he774522_0
bkcharts                  0.2                      py38_0
blas                      1.0                         mkl
bleach                    3.2.1                      py_0
blosc                     1.20.0               h7bd577a_0
bokeh                     2.2.1                    py38_0
boto                      2.49.0                   py38_0
bottleneck                1.3.2            py38h2a96729_1
brotlipy                  0.7.0           py38he774522_1000
bzip2                     1.0.8                he774522_0
ca-certificates           2020.7.22                     0
cached-property           1.5.1                      py_1
cartopy                   0.18.0           py38hd77ba2b_0
certifi                   2020.6.20                py38_0
cffi                      1.14.2           py38h7a1dbc1_0
cfitsio                   3.470                he774522_5
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cloudpickle               1.6.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.3                      py_0
comtypes                  1.1.7                 py38_1001
conda                     4.8.4                    py38_0
conda-build               3.20.2                   py38_0
conda-pack                0.5.0                      py_0
conda-package-handling    1.6.1            py38h62dcd97_0
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              3.1              py38h7a1dbc1_0
curl                      7.69.1               h2a8f88b_0
customimporter            2.0.2                      py_0    <unknown>
cycler                    0.10.0                   py38_0
cython                    0.29.21          py38ha925a31_0
cytoolz                   0.10.1           py38he774522_0
dask                      2.26.0                     py_0
dask-core                 2.26.0                     py_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
distributed               2.26.0                   py38_0
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
expat                     2.2.9                h33f27b4_2
fastcache                 1.1.0            py38he774522_0
filelock                  3.0.12                     py_0
flake8                    3.8.3                      py_0
flask                     1.1.2                      py_0
freetype                  2.10.2               hd328e21_0
freexl                    1.0.5                hfa6e2cd_0
fsspec                    0.8.0                      py_0
future                    0.18.2                   py38_1
gdal                      3.0.2            py38h2fee047_7    conda-forge
geos                      3.8.0                h33f27b4_0
geotiff                   1.5.1                h5770a2b_1
get_terminal_size         1.0.0                h38e98db_0
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
gevent                    20.6.2           py38he774522_0
glib                      2.65.0               he4de6d7_0    conda-forge
glob2                     0.7                        py_0
gmpy2                     2.0.8            py38h7edee0f_3
greenlet                  0.4.16           py38he774522_0
h5py                      2.10.0          nompi_py38h422b98e_102    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
iniconfig                 1.0.1                      py_0
intel-openmp              2020.1                      216
intervaltree              3.1.0                      py_0
ipdb                      0.13.3             pyh9f0ad1d_0    conda-forge
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.18.1           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
isort                     5.4.2                    py38_0
itsdangerous              1.1.0                      py_0
jdcal                     1.4.1                      py_0
jedi                      0.17.1                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9d                   he774522_0    conda-forge
jplephem                  2.15               pyh2f6353c_0    conda-forge
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py38_0
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.2.6                      py_0
jupyterlab_server         1.2.0                      py_0
kealib                    1.4.13               hd6dc3df_0    conda-forge
keyring                   21.4.0                   py38_0
kiwisolver                1.2.0            py38h74a9793_0
krb5                      1.17.1               hc04afaa_0
lazy-object-proxy         1.4.3            py38he774522_0
libarchive                3.4.2                h5e25573_0
libblas                   3.8.0                    16_mkl    conda-forge
libboost                  1.67.0               hd9e427e_4
libcblas                  3.8.0                    16_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0
libcurl                   7.69.1               h2a8f88b_0
libffi                    3.2.1             ha925a31_1007    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgdal                   3.0.2                ha9114c6_7    conda-forge
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libnetcdf                 4.7.3           nompi_hc957ea6_101    conda-forge
libopenblas               0.3.10          pthreads_h1662909_4    conda-forge
libpng                    1.6.37               h2a8f88b_0
libpq                     12.2                 h3235a2c_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libspatialite             4.3.0a               h7ffb84d_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
libxml2                   2.9.10               h464c3ec_1
libxslt                   1.1.34               he774522_0
llvm-meta                 5.0.0                         0    conda-forge
llvmlite                  0.31.0           py38ha925a31_0
locket                    0.2.0                    py38_1
lxml                      4.5.2            py38h1350720_0
lz4-c                     1.9.2                h62dcd97_1
lzo                       2.10                 he774522_2
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38he774522_0
matplotlib                3.3.1                         0
matplotlib-base           3.3.1            py38hba9282a_0
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.1                      216
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.2.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.2                      py_0
more-itertools            8.5.0                      py_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.1.0                    py38_0
msgpack-python            1.0.0            py38h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py38_0
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.7                      py_0
networkx                  2.5                        py_0
nltk                      3.5                        py_0
nose                      1.3.7                    py38_2
notebook                  6.1.1                    py38_0
numba                     0.48.0           py38h47e9c7a_0
numexpr                   2.7.1            py38h25d0782_0
numpy                     1.19.1           py38h5510c5b_0
numpy-base                1.19.1           py38ha3acd2a_0
numpydoc                  1.1.0                      py_0
olefile                   0.46                       py_0
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openpyxl                  3.0.5                      py_0
openssl                   1.1.1g               he774522_1
owslib                    0.20.0                     py_0
packaging                 20.4                       py_0
pandas                    1.1.1            py38ha925a31_0
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py38_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
path                      15.0.0                   py38_0
path.py                   12.5.0                        0
pathlib2                  2.3.5                    py38_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py38_0
pcre                      8.44                 ha925a31_0
pep8                      1.7.1                    py38_0
pexpect                   4.8.0                    py38_0
pickleshare               0.7.5                 py38_1000
pillow                    7.2.0            py38hcc1f983_0
pip                       20.2.2                   py38_0
pkginfo                   1.5.0.1                  py38_0
plotly                    4.10.0                     py_0
pluggy                    0.13.1                   py38_0
ply                       3.11                     py38_0
poliastro                 0.14.0                     py_1    conda-forge
poppler                   0.67.0               h1707e21_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 h3235a2c_0
powershell_shortcut       0.0.1                         3
progressbar2              3.37.1                   py38_0
proj                      6.2.1                h9f7ef89_0
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.7                      py_0
prompt_toolkit            3.0.7                         0
psutil                    5.7.2            py38he774522_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py38ha925a31_0
pycodestyle               2.6.0                      py_0
pycosat                   0.6.3            py38he774522_0
pycparser                 2.20                       py_2
pycurl                    7.43.0.5         py38h7a1dbc1_0
pydocstyle                5.1.1                      py_0
pyepsg                    0.4.0                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.7.0                      py_0
pykdtree                  1.3.1           py38h8c2d366_1002
pylint                    2.6.0                    py38_0
pynacl                    1.4.0            py38h62dcd97_1
pyodbc                    4.0.30           py38ha925a31_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyperclip                 1.8.0              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38hcfa1391_1
pyqt                      5.12.3           py38h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadline                2.1                      py38_1
pyrsistent                0.17.3           py38he774522_0
pyshp                     2.1.2                      py_0
pyside2                   5.13.2           py38hfa7ce6d_2    conda-forge
pysocks                   1.7.1                    py38_0
pytables                  3.6.1            py38h26f9782_1    conda-forge
pytest                    6.0.2                    py38_0
pytest-runner             5.2                        py_0
python                    3.8.5                h5fd99cc_1
python-dateutil           2.8.1                      py_0
python-docx               0.8.10                     py_0    conda-forge
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.35.1                     py_0
python-libarchive-c       2.9                        py_0
python-utils              2.3.0                    py38_0
pytz                      2020.1                     py_0
pywavelets                1.1.1            py38he774522_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38he774522_1
pyzmq                     19.0.1           py38ha925a31_1
qdarkstyle                2.8.1                      py_0
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.6                      py_0
qtpy                      1.9.0                      py_0
regex                     2020.7.14        py38he774522_0
requests                  2.24.0                     py_0
retrying                  1.3.3                      py_2
ripgrep                   11.0.2                        0
rope                      0.17.0                     py_0
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.87          py38he774522_1
scikit-image              0.16.2           py38h47e9c7a_0
scikit-learn              0.23.2           py38h47e9c7a_0
scipy                     1.5.0            py38h9439919_0
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py38_0
setuptools                49.6.0                   py38_0
shapely                   1.7.1            py38h210f175_0
simplegeneric             0.8.1                    py38_2
singledispatch            3.4.0.3                  py38_0
sip                       4.19.24          py38ha925a31_0
six                       1.15.0                     py_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.0.0                      py_0
sortedcollections         1.2.1                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.2.1                      py_0
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-websupport  1.2.4                      py_0
spyder                    4.1.5                    py38_0
spyder-kernels            1.9.4                    py38_0
sqlalchemy                1.3.19           py38he774522_0
sqlite                    3.33.0               h2a8f88b_0
statsmodels               0.11.1           py38he774522_0
sympy                     1.6.2                    py38_0
tbb                       2020.2               h74a9793_0
tblib                     1.7.0                      py_0
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tiledb                    1.7.0                h0b90766_4    conda-forge
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
toolz                     0.10.0                     py_0
tornado                   6.0.4            py38he774522_1
tqdm                      4.48.2                     py_0
traitlets                 4.3.3                    py38_0
typing_extensions         3.7.4.3                    py_0
ujson                     3.1.0            py38ha925a31_0
unicodecsv                0.14.1                   py38_0
urllib3                   1.25.10                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py38_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1                      py_0
wheel                     0.35.1                     py_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0                    py38_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py38he774522_0
xerces-c                  3.2.2                ha925a31_0
xlrd                      1.2.0                      py_0
xlsxwriter                1.3.3                      py_0
xlwings                   0.20.5                   py38_0
xlwt                      1.3.0                    py38_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_3
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py38_1
zope.event                4.4                      py38_0
zope.interface            5.1.0            py38he774522_0
zstd                      1.4.5                h04227a9_0

**Comment by AaronFaltesek** [comment] 2020-09-18 23:34
I'm having the same error:

`Collecting packages...
CondaPackError: 
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- pandas='0.20.3'
- numpy='1.13.1'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).`

pip list:
`Package                       Version
----------------------------- ---------
alabaster                     0.7.10
atomicwrites                  1.4.0
attrs                         20.2.0
Babel                         2.5.0
boto3                         1.4.5
botocore                      1.5.92
certifi                       2016.2.28
cffi                          1.14.3
coverage                      5.3
cryptography                  3.0
docutils                      0.14
flatten-dict                  0.3.0
imagesize                     0.7.1
importlib-metadata            1.7.0
Jinja2                        2.9.6
jmespath                      0.9.0
MarkupSafe                    1.0
more-itertools                8.5.0
numpy                         1.19.2
packaging                     16.8
pandas                        0.25.3
pathlib2                      2.3.5
pip                           20.2.3
pluggy                        0.13.1
psycopg2                      2.7.1
psycopg2-binary               2.8.5
py                            1.9.0
py4j                          0.10.6
pyarrow                       0.14.1
pycparser                     2.20
Pygments                      2.2.0
pypandoc                      1.4
pyparsing                     2.2.0
pyspark                       2.2.0
pytest                        5.0.1
pytest-cov                    2.7.1
pytest-runner                 5.1
python-dateutil               2.6.1
pytz                          2017.2
PyYAML                        5.3.1
requests                      2.14.2
s3transfer                    0.1.10
setuptools                    36.4.0
six                           1.10.0
snowballstemmer               1.2.1
Sphinx                        2.1.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
uc-data-index-utils           0.1.0
wcwidth                       0.2.5
wheel                         0.29.0
zipp                          3.1.0`

conda list:
`# packages in environment at /opt/oss/conda3/envs/py36-uc-val-pandas:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge  
_openmp_mutex             4.5                       1_gnu  
alabaster                 0.7.10                   py36_0    /
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     20.2.0                   pypi_0    pypi
babel                     2.5.0                    py36_0    /
blas                      1.0                         mkl    /
boto3                     1.4.5                    py36_0    /
botocore                  1.5.92                   py36_0    /
certifi                   2016.2.28                py36_0    /
cffi                      1.14.3                   pypi_0    pypi
coverage                  5.3                      pypi_0    pypi
cryptography              3.0                      pypi_0    pypi
docutils                  0.14                     py36_0    /
flatten-dict              0.3.0                    pypi_0    pypi
gmp                       6.1.0                         0    /
imagesize                 0.7.1                    py36_0    /
importlib-metadata        1.7.0                    pypi_0    pypi
jinja2                    2.9.6                    py36_0    /
jmespath                  0.9.0                    py36_0    /
libffi                    3.2.1                         1    /
libgcc-ng                 9.3.0               h24d8f2e_16  
libgomp                   9.3.0               h24d8f2e_16  
libpq                     9.5.4                         0    /
markupsafe                1.0                      py36_0    /
mkl                       2017.0.3                      0    /
more-itertools            8.5.0                    pypi_0    pypi
numpy                     1.19.2                   pypi_0    pypi
openssl                   1.0.2l                        0    /
packaging                 16.8                     py36_0    /
pandas                    0.25.3                   pypi_0    pypi
pandoc                    1.15.0.6                      0    /
pathlib2                  2.3.5                    pypi_0    pypi
pip                       20.2.3                     py_0  
pluggy                    0.13.1                   pypi_0    pypi
psycopg2                  2.7.1                    py36_0    /
psycopg2-binary           2.8.5                    pypi_0    pypi
py                        1.9.0                    pypi_0    pypi
py4j                      0.10.6                   py36_0    /
pyarrow                   0.14.1                   pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.2.0                    py36_0    /
pypandoc                  1.4                      py36_0    /
pyparsing                 2.2.0                    py36_0    /
pyspark                   2.2.0                    py36_0    /
pytest                    5.0.1                    pypi_0    pypi
pytest-cov                2.7.1                    pypi_0    pypi
pytest-runner             5.1                      pypi_0    pypi
python                    3.6.0                         0    /
python-dateutil           2.6.1                    py36_0    /
python_abi                3.6                     1_cp36m  
pytz                      2017.2                   py36_0    /
pyyaml                    5.3.1            py36h8c4c3a4_0  
readline                  6.2                           2    /
requests                  2.14.2                   py36_0    /
s3transfer                0.1.10                   py36_0    /
setuptools                36.4.0                   py36_1    /
six                       1.10.0                   py36_0    /
snowballstemmer           1.2.1                    py36_0    /
sphinx                    2.1.2                      py_0  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sqlite                    3.13.0                        0    /
tk                        8.5.18                        0    /
uc-data-index-utils       0.1.0                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.29.0                   py36_0    /
xz                        5.2.3                         0    /
yaml                      0.2.5                h516909a_0  
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11                        0    /`

**Comment by mcg1969** [comment] 2020-09-18 23:39
@Phillip-M-Feldman please try the `--ignore-missing-files` in your case. I've noticed this problem with the Python package as well. It's a duplicate of #145 .

@AaronFaltesek that is, to be frank, _way_ too many Pip packages. Conda-pack is intended to pack environments that were built almost exclusively with conda. In particular, pip packages with binary files have a high probability of failure. You too can try `--ignore-missing-files` but I would be very concerned that this just will not work for your environment.

**Comment by Phillip-M-Feldman** [comment] 2020-09-19 17:54
WIth the --ignore-missing-files option, I get the following popup error:
"The procedure entry point ?PyWinObject_FromULARGE_INTEGER@@YAPEAU_object@
@AEAT_ULARGE_INTEGER@@@Z could not be located in the dynamic link library
C:\PROGRAM~1\Anaconda3\Library\bin\pythoncom37.dll"

**Comment by mcg1969** [comment] 2020-09-20 17:17
Hmm, I honestly have no idea what this means. But to help us isolate the issue, can you please try Python 3.8.3 instead of Python 3.8.5? Something _did_ change with Python 3.8.5 that I cannot fully understand.

It sounds like `--ignore-missing-files` in this case just got you past one error and landed you into another.

I still feel like your use case may be better served by `constructor` instead of `conda-pack`, but that is a larger conversation outside of the scope of this issue tracker :-)

**Comment by mcg1969** [comment] 2020-09-20 17:25
I think the problem is actually specific to that particular Python 3.8.5 package. I'm talking to the Anaconda Distribution team about it.

**Comment by mcg1969** [comment] 2020-09-20 20:00
I've fixed the missing files issue specific to Python 3.8.5 in #151 

@Phillip-M-Feldman I did some Googling of the specific issue with your Python environment and found the first link below, which in turn led me to the second. 

https://stackoverflow.com/a/59884311/1599393
https://github.com/conda/conda/issues/9003#issuecomment-553529174

**Comment by Phillip-M-Feldman** [comment] 2020-09-21 05:18
That's tremendous.  Thank you!

**Comment by mcg1969** [comment] 2020-11-14 23:07
I'm going to close this issue because the original description really is outside of the scope of conda-pack. I've tried to improve the documentation in conda-pack to make this clear. It a conda environment cannot be cloned, it cannot be conda-pack'ed, either. Conda's cloning functionality is a little more powerful in that it can re-download packages into the package cache that are needed. But still, if that's not possible, neither cloning nor conda-pack will work.

**Closed by mcg1969** 2020-11-14 23:07 UTC

**Comment by nscozzaro** [comment] 2020-12-08 18:14
Yes I was also getting this error and fixed it by downgrading my python version to 3.7:
```
conda activate my_env
conda install python=3.7
```

**Comment by Phillip-M-Feldman** [comment] 2020-12-08 23:51
This is not a great workaround.  I've spoken with folks at Anaconda and
they have boosted the priority of getting this problem solved.

**Comment by skamensky** [comment] 2020-12-19 20:04
I was using the latest version of miniconda and was seeing a similar error, but only the python package was showing up as problematic.

```
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- python='3.8.5'

```
After seeing @nscozzaro comment about changing python versions, I used miniconda with python3.7 instead and it worked perfectly fine.

**Comment by Phillip-M-Feldman** [comment] 2020-12-19 20:07
This is the behavior that I've seen recently as well.

**Comment by hejianchao** [comment] 2021-01-06 06:04
Is there any progress?

**Comment by davegravy** [comment] 2021-01-10 21:43
Steps to reproduce on EC2 running a fresh Amazon Linux 2 AMI:

(run as root user)
```
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
bash /tmp/miniconda.sh -b -p $HOME/miniconda
rm /tmp/miniconda.sh
echo -e '\nexport PATH=$HOME/miniconda/bin:$PATH' >> $HOME/.bashrc
source $HOME/.bashrc
conda update conda -y
conda install -y conda-pack
conda pack -q -o $HOME/environment.tar.gz
```

Produces:

> CondaPackError:
> Files managed by conda were found to have been deleted/overwritten in the following packages:
> 
> python='3.8.5'

NOTE: adding `--ignore-missing-files` resolves.
