### ISSUE TITLE
Windows package gives "Access is denied"

### ISSUE THREAD

**Issue by dwr-psandhu** [conda/conda-pack#101] opened 2020-02-06 22:12 UTC
OS: Windows 10
Packaging an environment gives a zip distribution. The permissions on the files are messed up and it gives "Access is denied" when trying to run any of the .exe files

Workaround: Unzip and use cygwin with chmod -R 777 on the unzipped contents and zip up again.

**Comment by mcg1969** [comment] 2020-07-03 19:31
Hmm, we successfully use zip to package up environments on Windows on frequent occasions. Can you please offer more specific details on how to reproduce this issue? What version of conda-pack? What version of zip? What packages are in the environment that you are packing? (conda list --export would be great). Thanks!

**Comment by mcg1969** [comment] 2020-09-07 04:36
I'm going to close this one simply because we don't have enough information to go on, and because we have plenty of evidence that .zip files are being successfully used in the wild. So I'm suspecting something unique about your particular configuration. But please do feel free to re-open if you can offer some of the specifics I asked for above, because if we _can_ pinpoint what is causing your particular systems to fail, we can and should fix it.

**Closed by mcg1969** 2020-09-07 04:36 UTC

**Comment by dwr-psandhu** [comment] 2020-12-31 21:06
@mcg1969 Turns out to be an issue with cygwin unzip causing the permission problem. Using 7zip or any windows unzip utility works fine.
