### ISSUE TITLE
conda unpack script not created in Windows

### ISSUE THREAD

**Issue by b-trav** [conda/conda-pack#86] opened 2019-08-14 04:24 UTC
If I install a new (2019-7) version of Anaconda in Windows, then create a new environment (based off jupyterlab), then try and pack this environment, a tar.gz file is created, but it contains no conda-unpack script. 

Just to expand, to assist with debugging, the following will produce a tar.gz file that DOES contain an unpack script on Windows:
```
conda create -n testenv python -y
conda pack -n testenv
```
but this will produce a tar.gz file that DOES NOT contain an unpack script on Windows:
```
conda create -n testlab jupyterlab -y
conda pack -n testlab
```
Here is the output from `conda info`:
```
    active environment : jupyterlab
    active env location : C:\Users\ben\Anaconda3\envs\jupyterlab
            shell level : 1
       user config file : C:\Users\ben\.condarc
 populated config files : 
          conda version : 4.7.11
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : C:\Users\ben\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\ben\Anaconda3\pkgs
                          C:\Users\ben\.conda\pkgs
                          C:\Users\ben\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ben\Anaconda3\envs
                          C:\Users\ben\.conda\envs
                          C:\Users\ben\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

Update: After some more investigation, I believe the problem is that the tar file reaches 2Gb, and then I think it stops storing files.

**Comment by b-trav** [comment] 2019-08-15 01:58
Just to expand on my last post to assist with debugging, the following will produce a tar.gz file that DOES contain an unpack script on Windows:
```
conda create -n testenv python -y
conda pack -n testenv
```
but this will produce a tar.gz file that DOES NOT contain an unpack script on Windows:
```
conda create -n testlab jupyterlab -y
conda pack -n testlab
```
Here is the output from `conda info`:
```
    active environment : jupyterlab
    active env location : C:\Users\ben\Anaconda3\envs\jupyterlab
            shell level : 1
       user config file : C:\Users\ben\.condarc
 populated config files : 
          conda version : 4.7.11
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : C:\Users\ben\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\ben\Anaconda3\pkgs
                          C:\Users\ben\.conda\pkgs
                          C:\Users\ben\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ben\Anaconda3\envs
                          C:\Users\ben\.conda\envs
                          C:\Users\ben\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by b-trav** [comment] 2019-08-28 05:17
Any easy work-around is to specify output as a .zip file. Perhaps conda pack can check which OS is being used and create .zip output by default in Windows.

**Comment by mcg1969** [comment] 2020-09-20 22:19
I know this is an old issue but I wanted to revisit it—and I cannot reproduce it with the example offered above. The environment created is only 497 MB on disk, before packing, and 139 MB packed. So I added tensorflow, pytorch::pytorch, pandas, spacy... that did it. :-)

**Comment by mcg1969** [comment] 2020-09-20 22:33
So with this modified environment, I have an environment that consumes 4.8GB on disk. Compressed down to just under 2.1GB in a .tar.gz file. Unpacking this tar file yields another 4.8GB environment, and the conda-pack script is included. I'll close this but if we can find an reproducible case I'm good to re-open this.

**Closed by mcg1969** 2020-09-20 22:33 UTC
