### ISSUE TITLE
libblas.so FileNotFoundError

### ISSUE THREAD

**Issue by ericdill** [conda/conda-pack#96] opened 2019-11-14 15:21 UTC
I'm trying to conda-pack an R environment:
```
conda create -y -n r-brd-env --copy r-sparklyr r-essentials r-changepoint r-zoo r-dplyr r-aws.s3 r-mixtools r-timedate r-data.table r-h2o r-tidyr r-rcpproll r-lubridate r-foreach r-domc conda-pack -c conda-forge

conda activate r-brd-env

conda-pack -o r_env.zip -d ./r_env.zip/
```

```
Collecting packages...
Packing environment at '/home/centos/miniconda/envs/r-brd-env' to 'r_env.zip'
[############                            ] | 32% Completed |  1min  4.3s
Traceback (most recent call last):
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/site-packages/conda_pack/cli.py", line 135, in main
    pack(name=args.name,
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/site-packages/conda_pack/core.py", line 462, in pack
    return env.pack(output=output, format=format, arcroot=arcroot,
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/site-packages/conda_pack/core.py", line 333, in pack
    packer.add(f)
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/site-packages/conda_pack/core.py", line 929, in add
    self.archive.add(file.source, file.target)
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/site-packages/conda_pack/formats.py", line 207, in add
    self._add(source, target)
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/site-packages/conda_pack/formats.py", line 291, in _add
    self.archive.write(source, target)
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/zipfile.py", line 1722, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/home/centos/miniconda/envs/r-brd-env/lib/python3.8/zipfile.py", line 509, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/centos/miniconda/pkgs/libblas-3.8.0-14_openblas/lib/libblas.so'

```

```
# packages in environment at /home/centos/miniconda/envs/r-brd-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_r-mutex                  1.0.1               anacondar_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
binutils_impl_linux-64    2.31.1               h7fc9f1b_2    conda-forge
binutils_linux-64         2.31.1              h6176602_12    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bwidget                   1.9.13                        0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py38_0    conda-forge
conda-pack                0.4.0                      py_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py38_1000    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_2    conda-forge
gcc_linux-64              7.3.0               h553295d_12    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_2    conda-forge
gfortran_linux-64         7.3.0               h553295d_12    conda-forge
glib                      2.58.3          py38h6f030ca_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_2    conda-forge
gxx_linux-64              7.3.0               h553295d_12    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
importlib_metadata        0.23                     py38_0    conda-forge
ipykernel                 5.1.3            py38h5ca1d4c_0    conda-forge
ipython                   7.9.0            py38h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.1                   py38_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.1.1                    py38_0    conda-forge
jupyter_client            5.3.3                    py38_1    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                hfc65ed5_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
make                      4.2.1             h14c3975_2004    conda-forge
markupsafe                1.1.1            py38h516909a_0    conda-forge
mistune                   0.8.4           py38h516909a_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
nbconvert                 5.6.1                    py38_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  6.0.1                    py38_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py38_0    conda-forge
pickleshare               0.7.5                 py38_1000    conda-forge
pip                       19.3.1                   py38_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyrsistent                0.15.5           py38h516909a_0    conda-forge
python                    3.8.0                h357f687_3    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pyzmq                     18.1.1           py38h1768529_0    conda-forge
r-askpass                 1.1               r36hcdcec82_1    conda-forge
r-assertthat              0.2.1             r36h6115d3f_1    conda-forge
r-aws.s3                  0.3.20          r36h6115d3f_1002    conda-forge
r-aws.signature           0.5.2             r36h6115d3f_0    conda-forge
r-backports               1.1.5             r36hcdcec82_0    conda-forge
r-base                    3.6.1                hba50c9b_5    conda-forge
r-base64enc               0.1_3           r36hcdcec82_1003    conda-forge
r-bitops                  1.0_6           r36hcdcec82_1003    conda-forge
r-boot                    1.3_23            r36h6115d3f_2    conda-forge
r-broom                   0.5.2             r36h6115d3f_1    conda-forge
r-callr                   3.3.2             r36h6115d3f_0    conda-forge
r-caret                   6.0_84            r36hcdcec82_1    conda-forge
r-cellranger              1.1.0           r36h6115d3f_1002    conda-forge
r-changepoint             2.2.2           r36h516909a_1003    conda-forge
r-class                   7.3_15          r36hcdcec82_1001    conda-forge
r-cli                     1.1.0             r36h6115d3f_2    conda-forge
r-clipr                   0.7.0             r36h6115d3f_0    conda-forge
r-cluster                 2.1.0             r36h9bbef5b_2    conda-forge
r-codetools               0.2_16          r36h6115d3f_1001    conda-forge
r-colorspace              1.4_1             r36hcdcec82_1    conda-forge
r-config                  0.3             r36h6115d3f_1002    conda-forge
r-crayon                  1.3.4           r36h6115d3f_1002    conda-forge
r-curl                    4.2               r36hcdcec82_0    conda-forge
r-data.table              1.12.6            r36hcdcec82_0    conda-forge
r-dbi                     1.0.0           r36h6115d3f_1002    conda-forge
r-dbplyr                  1.4.2             r36h6115d3f_1    conda-forge
r-digest                  0.6.22            r36h0357c0b_0    conda-forge
r-domc                    1.3.6                     r36_0    conda-forge
r-dplyr                   0.8.3             r36h0357c0b_3    conda-forge
r-ellipsis                0.3.0             r36hcdcec82_0    conda-forge
r-essentials              3.6                    r36_2001    conda-forge
r-evaluate                0.14              r36h6115d3f_1    conda-forge
r-fansi                   0.4.0           r36hcdcec82_1001    conda-forge
r-fastmap                 1.0.1             r36h0357c0b_0    conda-forge
r-forcats                 0.4.0             r36h6115d3f_1    conda-forge
r-foreach                 1.4.7             r36h6115d3f_0    conda-forge
r-foreign                 0.8_72            r36hcdcec82_0    conda-forge
r-forge                   0.2.0             r36h6115d3f_1    conda-forge
r-formatr                 1.7               r36h6115d3f_1    conda-forge
r-fs                      1.3.1             r36h0357c0b_1    conda-forge
r-generics                0.0.2           r36h6115d3f_1002    conda-forge
r-ggplot2                 3.2.1             r36h6115d3f_0    conda-forge
r-gistr                   0.4.2           r36h6115d3f_1002    conda-forge
r-glmnet                  2.0_18            r36h9bbef5b_2    conda-forge
r-glue                    1.3.1             r36hcdcec82_1    conda-forge
r-gower                   0.2.1             r36hcdcec82_1    conda-forge
r-gtable                  0.3.0             r36h6115d3f_2    conda-forge
r-h2o                     3.26.0.2          r36h6115d3f_0    defaults
r-haven                   2.2.0             r36hde08347_0    conda-forge
r-hexbin                  1.28.0            r36h9bbef5b_0    conda-forge
r-highr                   0.8               r36h6115d3f_1    conda-forge
r-hms                     0.5.2             r36h6115d3f_0    conda-forge
r-htmltools               0.4.0             r36h0357c0b_0    conda-forge
r-htmlwidgets             1.5.1             r36h6115d3f_0    conda-forge
r-httpuv                  1.5.2             r36h0357c0b_1    conda-forge
r-httr                    1.4.1             r36h6115d3f_1    conda-forge
r-ipred                   0.9_9             r36hcdcec82_1    conda-forge
r-irdisplay               0.7                    r36_1001    conda-forge
r-irkernel                1.0.2             r36h6115d3f_2    conda-forge
r-iterators               1.0.12            r36h6115d3f_0    conda-forge
r-jsonlite                1.6             r36hcdcec82_1001    conda-forge
r-kernsmooth              2.23_15         r36h9bbef5b_1004    conda-forge
r-knitr                   1.26              r36h6115d3f_0    conda-forge
r-labeling                0.3             r36h6115d3f_1002    conda-forge
r-later                   1.0.0             r36h0357c0b_0    conda-forge
r-lattice                 0.20_38         r36hcdcec82_1002    conda-forge
r-lava                    1.6.6             r36h6115d3f_0    conda-forge
r-lazyeval                0.2.2             r36hcdcec82_1    conda-forge
r-lifecycle               0.1.0             r36h6115d3f_0    conda-forge
r-lubridate               1.7.4           r36h0357c0b_1002    conda-forge
r-magrittr                1.5             r36h6115d3f_1002    conda-forge
r-maps                    3.3.0           r36hcdcec82_1003    conda-forge
r-markdown                1.1               r36hcdcec82_0    conda-forge
r-mass                    7.3_51.4          r36hcdcec82_1    conda-forge
r-matrix                  1.2_17            r36hcdcec82_1    conda-forge
r-mgcv                    1.8_29            r36hcdcec82_0    conda-forge
r-mime                    0.7               r36hcdcec82_1    conda-forge
r-mixtools                1.1.0           r36hcdcec82_1003    conda-forge
r-modelmetrics            1.2.2             r36h0357c0b_1    conda-forge
r-modelr                  0.1.5             r36h6115d3f_0    conda-forge
r-munsell                 0.5.0           r36h6115d3f_1002    conda-forge
r-nlme                    3.1_141           r36h9bbef5b_1    conda-forge
r-nnet                    7.3_12          r36hcdcec82_1003    conda-forge
r-numderiv                2016.8_1.1        r36h6115d3f_1    conda-forge
r-openssl                 1.4.1             r36h9c8475f_0    conda-forge
r-pbdzmq                  0.3_3           r36h559a7a4_1002    conda-forge
r-pillar                  1.4.2             r36h6115d3f_2    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_0    conda-forge
r-plogr                   0.2.0           r36h6115d3f_1002    conda-forge
r-plyr                    1.8.4           r36h0357c0b_1003    conda-forge
r-prettyunits             1.0.2           r36h6115d3f_1002    conda-forge
r-processx                3.4.1             r36hcdcec82_0    conda-forge
r-prodlim                 2019.10.13        r36h0357c0b_0    conda-forge
r-progress                1.2.2             r36h6115d3f_1    conda-forge
r-promises                1.1.0             r36h0357c0b_0    conda-forge
r-pryr                    0.1.4           r36h0357c0b_1003    conda-forge
r-ps                      1.3.0           r36hcdcec82_1001    conda-forge
r-purrr                   0.3.3             r36hcdcec82_0    conda-forge
r-quantmod                0.4_15            r36h6115d3f_1    conda-forge
r-r2d3                    0.2.3           r36h6115d3f_1001    conda-forge
r-r6                      2.4.1             r36h6115d3f_0    conda-forge
r-randomforest            4.6_14          r36h9bbef5b_1002    conda-forge
r-rappdirs                0.3.1           r36hcdcec82_1003    conda-forge
r-rbokeh                  0.5.0           r36h6115d3f_1002    conda-forge
r-rcolorbrewer            1.1_2           r36h6115d3f_1002    conda-forge
r-rcpp                    1.0.3             r36h0357c0b_0    conda-forge
r-rcpproll                0.3.0           r36h0357c0b_1001    conda-forge
r-rcurl                   1.95_4.12         r36hcdcec82_1    conda-forge
r-readr                   1.3.1           r36h0357c0b_1002    conda-forge
r-readxl                  1.3.1             r36h0357c0b_2    conda-forge
r-recipes                 0.1.7             r36h6115d3f_0    conda-forge
r-recommended             3.6                    r36_1003    conda-forge
r-rematch                 1.0.1           r36h6115d3f_1002    conda-forge
r-repr                    1.0.1             r36h6115d3f_1    conda-forge
r-reprex                  0.3.0             r36h6115d3f_1    conda-forge
r-reshape2                1.4.3           r36h0357c0b_1004    conda-forge
r-rlang                   0.4.1             r36hcdcec82_0    conda-forge
r-rmarkdown               1.17              r36h6115d3f_0    conda-forge
r-rpart                   4.1_15            r36hcdcec82_1    conda-forge
r-rprojroot               1.3_2           r36h6115d3f_1002    conda-forge
r-rstudioapi              0.10              r36h6115d3f_2    conda-forge
r-rvest                   0.3.5             r36h6115d3f_0    conda-forge
r-scales                  1.0.0           r36h0357c0b_1002    conda-forge
r-segmented               1.0_0             r36h6115d3f_1    conda-forge
r-selectr                 0.4_1           r36h6115d3f_1001    conda-forge
r-shiny                   1.4.0             r36h6115d3f_0    conda-forge
r-sourcetools             0.1.7           r36he1b5a44_1001    conda-forge
r-sparklyr                1.0.4             r36h6115d3f_0    conda-forge
r-spatial                 7.3_11          r36hcdcec82_1003    conda-forge
r-squarem                 2017.10_1       r36h6115d3f_1002    conda-forge
r-stringi                 1.4.3             r36h0e574ca_3    conda-forge
r-stringr                 1.4.0             r36h6115d3f_1    conda-forge
r-survival                2.44_1.1          r36hcdcec82_1    conda-forge
r-sys                     3.3               r36hcdcec82_0    conda-forge
r-tibble                  2.1.3             r36hcdcec82_1    conda-forge
r-tidyr                   1.0.0             r36h0357c0b_0    conda-forge
r-tidyselect              0.2.5           r36h0357c0b_1001    conda-forge
r-tidyverse               1.2.1           r36h6115d3f_1002    conda-forge
r-timedate                3043.102        r36h6115d3f_1001    conda-forge
r-tinytex                 0.17              r36h6115d3f_0    conda-forge
r-ttr                     0.23_5            r36hcdcec82_0    conda-forge
r-utf8                    1.1.4           r36hcdcec82_1001    conda-forge
r-uuid                    0.1_2           r36hcdcec82_1002    conda-forge
r-vctrs                   0.2.0             r36hcdcec82_1    conda-forge
r-viridislite             0.3.0           r36h6115d3f_1002    conda-forge
r-whisker                 0.4               r36h6115d3f_0    conda-forge
r-withr                   2.1.2           r36h6115d3f_1001    conda-forge
r-xfun                    0.11              r36h6115d3f_0    conda-forge
r-xml2                    1.2.2             r36h0357c0b_0    conda-forge
r-xtable                  1.8_4             r36h6115d3f_2    conda-forge
r-xts                     0.11_2            r36hcdcec82_1    conda-forge
r-yaml                    2.2.0           r36hcdcec82_1002    conda-forge
r-zeallot                 0.1.0           r36h6115d3f_1001    conda-forge
r-zoo                     1.8_6             r36hcdcec82_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
sed                       4.7               h1bed415_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.6.0                   py38_1    conda-forge
six                       1.13.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
terminado                 0.8.3                    py38_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
tornado                   6.0.3            py38h516909a_0    conda-forge
traitlets                 4.3.3                    py38_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py38_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge
```

Not sure how to debug or resolve this. Any suggestions?

**Comment by xhochy** [comment] 2020-05-15 11:26
Is `/home/centos/miniconda/pkgs/libblas-3.8.0-14_openblas/lib/libblas.so` a symlink? Could be that they aren't supported in zipfiles and only work with tars?

**Comment by mcg1969** [comment] 2020-07-03 19:32
I'm guessing this is a duplicate of #99 ...

**Closed by mcg1969** 2020-07-03 19:32 UTC

**Comment by mcg1969** [comment] 2020-07-03 19:33
@xhochy yes, it is indeed a symbolic link.
