### ISSUE TITLE
ipopt does not wotk

### ISSUE THREAD

**Issue by Albert65** [conda/conda-pack#139] opened 2020-07-27 14:32 UTC
Dear All,

I installed ipopt and related packages on the source Redhat 7.7/64:
```
conda update conda -y && \
conda install -y numpy scipy matplotlib psutil joblib opencv && \
conda install -y -c conda-forge ipopt cyipopt pycalphad cvxpy conda-pack && \
conda update conda -y
``` 
Then I packed (as "conda pack") and sent Conda environment to the target machine equipped with Redhat 7.8/64.
Packages like opencv or cvxpy can be imported, but ipopt is not found, although it works fine on the source side.
Btw, on the source system cv2 package has version 4.3, but on the target one the version is 4.2.

**Comment by mcg1969** [comment] 2020-09-20 21:35
I'm unable to reproduce this. Granted I'm on Ubuntu 18. But I did the following:
```
conda create -n packtest conda numpy scipy matplotlib psutil joblib opencv
conda install -y -c conda-forge -n packtest ipopt cyipopt pycalphad cvxpy conda-pack
conda install -n packtest conda
conda activate packtest
conda-pack -n packtest
mkdir tmpenv
tar xfz packtest.tar.gz -C ./tmpenv
conda activate ./tmpenv
python
import ipopt
```

**Comment by mcg1969** [comment] 2020-11-14 23:01
I'm going to close this one simply for hygeine reasons but of course will be happy to see it re-opened or a new issue created if necessary.

**Closed by mcg1969** 2020-11-14 23:01 UTC
