### ISSUE TITLE
Pack claims conda files were overridden with pip, but pip was not used

### ISSUE THREAD

**Issue by carterbox** [conda/conda-pack#78] opened 2019-07-03 16:52 UTC
I am trying to create a conda-pack for this environment:

```yaml
name: tomopy-short-course
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - dxchange
  - jupyter
  - python 3*
  - tomopy 1.5*
```
I used the following command to create a conda-pack:
```
conda pack -n tomopy-short-course
Collecting packages...
CondaPackError:
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- attrs='19.1.0'
- backcall='0.1.0'
- bleach='3.1.0'
- cloudpickle='1.2.1'
- colorama='0.4.1'
- cycler='0.10.0'
- dask-core='2.0.0'
- decorator='4.4.0'
- defusedxml='0.5.0'
- dxfile='0.5'
- edffile='5.0.0'
- ipython_genutils='0.2.0'
- ipywidgets='7.5.0'
- jinja2='2.10.1'
- jupyter='1.0.0'
- jupyter_client='5.2.4'
- jupyter_console='6.0.0'
- jupyter_core='4.4.0'
- nbconvert='5.5.0'
- nbformat='4.4.0'
- networkx='2.3'
- olefile='0.46'
- pandocfilters='1.4.2'
- parso='0.5.0'
- prometheus_client='0.7.1'
- prompt_toolkit='2.0.9'
- pygments='2.4.2'
- pyparsing='2.4.0'
- python-dateutil='2.8.0'
- qtconsole='4.5.1'
- send2trash='1.5.0'
- spefile='1.6'
- testpath='0.4.2'
- tomopy='1.5.1'
- toolz='0.9.0'
- tqdm='4.32.2'
- wcwidth='0.1.7'
- webencodings='0.5.1'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).
```
I get this error message claiming that these packages were conflicted. None of these packages are duplicated or installed with pip, so I have no idea why I'm getting this error.

Here is information about my conda installation.
```
active environment : base
    active env location : C:\Users\dchin\Miniconda3
            shell level : 1
       user config file : C:\Users\dchin\.condarc
 populated config files : C:\Users\dchin\.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Users\dchin\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\dchin\Miniconda3\pkgs
                          C:\Users\dchin\.conda\pkgs
                          C:\Users\dchin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\dchin\Miniconda3\envs
                          C:\Users\dchin\.conda\envs
                          C:\Users\dchin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by angelo-peronio** [comment] 2019-07-11 12:22
Same issue here:
```
(base) λ conda pack -n test_env
Collecting packages...
CondaPackError:
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- appdirs='1.4.3'
- attrs='19.1.0'
- black='19.3b0'
- click='7.0'
- toml='0.10.0'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).
```

The environment I was trying to pack is just python + black:
```
(base) λ conda list -n test_env
# packages in environment at C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3\envs\test_env:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                      py_1    conda-forge
attrs                     19.1.0                     py_0    conda-forge
black                     19.3b0                     py_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
click                     7.0                        py_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_0    conda-forge
toml                      0.10.0                     py_0    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_4    defaults
wheel                     0.33.4                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
```

My conda installation:
```
(base) λ conda info

     active environment : base
    active env location : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3
            shell level : 1
       user config file : C:\Users\angelo.peronio\.condarc
 populated config files : C:\Users\angelo.peronio\.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\angelo.peronio\.conda\pkgs
                          C:\Users\angelo.peronio\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\angelo.peronio\.conda\envs
                          C:\Users\angelo.peronio\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

```
λ conda list conda-pack
# packages in environment at C:\Users\angelo.peronio\AppData\Local\Continuum\miniconda3:
# Name                    Version                   Build  Channel
conda-pack                0.3.1                      py_0    conda-forge
[...]
```

In another, less minimal environment, I had the same problem involving the packages:
```
- appdirs='1.4.3'
- asteval='0.9.14'
- attrs='19.1.0'
- backcall='0.1.0'
- black='19.3b0'
- click='7.0'
- cloudpickle='1.2.1'
- colorama='0.4.1'
- cycler='0.10.0'
- decorator='4.4.0'
- flake8-docstrings='1.3.0'
- flake8-polyfill='1.0.2'
- ipython_genutils='0.2.0'
- jupyter_client='5.3.1'
- jupyter_core='4.4.0'
- lmfit='0.9.13'
- mccabe='0.6.1'
[...]
- parso='0.5.0'
- prompt_toolkit='2.0.9'
- pycodestyle='2.5.0'
- pyflakes='2.1.1'
- pygments='2.4.2'
- pyparsing='2.4.0'
- python-dateutil='2.8.0'
- pytz='2019.1'
- rope='0.14.0'
- snowballstemmer='1.9.0'
- toml='0.10.0'
- wcwidth='0.1.7'
```

**Comment by jcrist** [comment] 2019-07-16 19:12
Apologies for the delay here. I'm unable to reproduce either of these on osx, I wonder if this is a windows specific issue. I'll try to spin up a VM and debug further.

**Comment by sephib** [comment] 2019-07-18 07:01
Hi,
This be similar to #63 (which is closed)
I"m running on :
>openSUSE Leap 42.3

setting up environment with 
> conda create -n test-pack python=3.6 -y -c conda-forge
> conda activate test-pack
> conda install -c conda-forge pandas-profiling

We get an error
> conda pack 
> CondaPackError: 
> Files managed by conda were found to have been deleted/overwritten in the
> following packages:
> - statsmodels='0.10.0'
>

**Comment by angelo-peronio** [comment] 2019-07-19 05:38
@jcrist , thank you. Let me know if I can help.

**Comment by jcrist** [comment] 2019-07-19 18:43
With #82 and #81 the following environments now work:

- The one with tomopy posted here: https://github.com/conda/conda-pack/issues/78#issue-463856423. Tomopy packages its LICENSE file in the root directory for some reason, which was causing issues.
- The one with black posted here: https://github.com/conda/conda-pack/issues/78#issuecomment-510462884. This was due to an issue with conda and `.nonadmin` files.

The one posted by @sephib above doesn't fail for me on osx, but I can't currently test on linux. If it still fails after the next release, please raise a new issue.

I'm going to finish a few cleanups and push a release out today. Thanks everyone for being patient. Closing.

**Closed by jcrist** 2019-07-19 18:43 UTC

**Comment by carterbox** [comment] 2019-07-21 00:52
Thanks, @jcrist.

**Comment by angelo-peronio** [comment] 2019-07-23 08:35
@jcrist , thank you! It works perfectly.

**Comment by sephib** [comment] 2019-07-25 11:36
@jcrist - I've updated to version 0.4.0 but still getting the same error   

> Collecting packages...
> CondaPackError: 
> Files managed by conda were found to have been deleted/overwritten in the
> following packages:
> 
> - statsmodels='0.10.1'

Is there any log that I can supply ?

**Comment by jcrist** [comment] 2019-07-25 13:38
I spun up a linux env to debug, and am unable to reproduce:

```
$ conda create -n test-pack python=3.6 pandas-profiling conda-pack -y -c conda-forge
...
$ conda activate test-pack
$ conda pack --version
conda-pack 0.4.0
$ conda pack
Collecting packages...
Packing environment at '/opt/miniconda/envs/test-pack' to 'test-pack.tar.gz'
[########################################] | 100% Completed | 33.9s
```

If you could reproduce, then create a new issue with the results of `conda list --export` for the failing environment that would be helpful.

**Comment by sephib** [comment] 2019-07-25 16:06
Hi,  
I ran the code again with `--force-reinstall` and still got an error.  
Here is the results of   `conda list --export`:  

> (test-pack) ds@linux-vnlc:~> conda list --export
>  This file may be used to create an environment using:
>  $ conda create --name <env> --file <this file>
>  platform: linux-64
> _libgcc_mutex=0.1=main
> asn1crypto=0.24.0=py36_1003
> astroid=2.2.5=py36_0
> astropy=3.2.1=py36h516909a_0
> atomicwrites=1.3.0=py_0
> attrs=19.1.0=py_0
> bleach=3.1.0=py_0
> ca-certificates=2019.6.16=hecc5488_0
> certifi=2019.6.16=py36_1
> cffi=1.12.3=py36h8022711_0
> chardet=3.0.4=py36_1003
> conda-pack=0.4.0=py_0
> confuse=1.0.0=py_0
> cryptography=2.7=py36h72c5cf5_0
> cycler=0.10.0=py_1
> dbus=1.13.6=he372182_0
> decorator=4.4.0=py_0
> defusedxml=0.5.0=py_1
> entrypoints=0.3=py36_1000
> expat=2.2.5=he1b5a44_1003
> fontconfig=2.13.1=h86ecdb6_1001
> freetype=2.10.0=he983fc9_0
> gettext=0.19.8.1=hc5be6a0_1002
> glib=2.58.3=h6f030ca_1002
> gst-plugins-base=1.14.5=h0935bb2_0
> gstreamer=1.14.5=h36ae1b5_0
> htmlmin=0.1.12=py_1
> icu=64.2=he1b5a44_0
> idna=2.8=py36_1000
> importlib_metadata=0.18=py36_0
> ipython_genutils=0.2.0=py_1
> isort=4.3.21=py36_0
> jinja2=2.10.1=py_0
> jpeg=9c=h14c3975_1001
> jsonschema=3.0.1=py36_0
> jupyter_client=5.3.1=py_0
> jupyter_core=4.4.0=py_0
> kiwisolver=1.1.0=py36hc9558a2_0
> lazy-object-proxy=1.4.1=py36h516909a_0
> libblas=3.8.0=10_openblas
> libcblas=3.8.0=10_openblas
> libffi=3.2.1=he1b5a44_1006
> libgcc-ng=9.1.0=hdf63c60_0
> libgfortran-ng=7.3.0=hdf63c60_0
> libiconv=1.15=h516909a_1005
> liblapack=3.8.0=10_openblas
> libopenblas=0.3.6=h6e990d7_5
> libpng=1.6.37=hed695b0_0
> libsodium=1.0.17=h516909a_0
> libstdcxx-ng=9.1.0=hdf63c60_0
> libuuid=2.32.1=h14c3975_1000
> libxcb=1.13=h14c3975_1002
> libxml2=2.9.9=hee79883_2
> llvmlite=0.29.0=py36hfd453ef_1
> markupsafe=1.1.1=py36h14c3975_0
> matplotlib=3.1.1=py36_1
> matplotlib-base=3.1.1=py36he7580a8_1
> mccabe=0.6.1=py_1
> missingno=0.4.2=py_0
> mistune=0.8.4=py36h14c3975_1000
> more-itertools=7.1.0=py_0
> nbconvert=5.5.0=py_0
> nbformat=4.4.0=py_1
> ncurses=6.1=hf484d3e_1002
> numba=0.45.0=py36hb3f55d8_0
> numpy=1.16.4=py36h95a1406_0
> openblas=0.3.6=h6e990d7_5
> openssl=1.1.1c=h516909a_0
> packaging=19.0=py_0
> pandas=0.25.0=py36hb3f55d8_0
> pandas-profiling=2.2.0=py_0
> pandoc=2.7.3=0
> pandocfilters=1.4.2=py_1
> patsy=0.5.1=py_0
> pcre=8.41=hf484d3e_1003
> phik=0.9.8=py_0
> pip=19.2.1=py36_0
> pluggy=0.12.0=py_0
> psutil=5.6.3=py36h516909a_0
> pthread-stubs=0.4=h14c3975_1001
> py=1.8.0=py_0
> pycparser=2.19=py36_1
> pygments=2.4.2=py_0
> pylint=2.3.1=py36_0
> pyopenssl=19.0.0=py36_0
> pyparsing=2.4.1=py_0
> pyqt=5.9.2=py36hcca6a23_0
> pyrsistent=0.15.3=py36h516909a_0
> pysocks=1.7.0=py36_0
> pytest=5.0.1=py36_1
> pytest-arraydiff=0.3=py_0
> pytest-astropy=0.5.0=py_0
> pytest-doctestplus=0.3.0=py_0
> pytest-openfiles=0.3.1=py_0
> pytest-pylint=0.14.0=py_0
> pytest-remotedata=0.3.1=py_0
> pytest-runner=5.1=py_0
> python=3.6.7=h357f687_1005
> python-dateutil=2.8.0=py_0
> pytz=2019.1=py_0
> pyyaml=5.1.1=py36h516909a_0
> pyzmq=18.0.2=py36h1768529_2
> qt=5.9.7=h0c104cb_3
> readline=8.0=hf8c457e_0
> requests=2.22.0=py36_1
> scipy=1.3.0=py36h921218d_0
> seaborn=0.9.0=py_1
> setuptools=41.0.1=py36_0
> sip=4.19.8=py36hf484d3e_1000
> six=1.12.0=py36_1000
> sqlite=3.29.0=hcee41ef_0
> statsmodels=0.10.1=py36hc1659b7_0
> testpath=0.4.2=py_1001
> tk=8.6.9=hed695b0_1002
> tornado=6.0.3=py36h516909a_0
> traitlets=4.3.2=py36_1000
> typed-ast=1.4.0=py36h516909a_0
> urllib3=1.25.3=py36_0
> wcwidth=0.1.7=py_1
> webencodings=0.5.1=py_1
> wheel=0.33.4=py36_0
> wrapt=1.11.2=py36h516909a_0
> xorg-libxau=1.0.9=h14c3975_0
> xorg-libxdmcp=1.1.3=h516909a_0
> xz=5.2.4=h14c3975_1001
> yaml=0.1.7=h14c3975_1001
> zeromq=4.3.2=he1b5a44_2
> zipp=0.5.1=py_0
> zlib=1.2.11=h516909a_1005
> 

Thx for all your time and great work!

**Comment by jcrist** [comment] 2019-07-25 16:08
Can you please open a new issue with that information?
